# Project 2 

In [10]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from helpers import *
from preprocessing import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Main 

In [2]:
DATA_Ux_PATH = 'data/u1_very_small.csv'
DATA_Uy_PATH = 'data/u2_very_small.csv'
Ux, ids_Ux= load_csv_data(DATA_Ux_PATH, sub_sample=False)
Uy, ids_Uy = load_csv_data(DATA_Uy_PATH, sub_sample=False)

In [3]:
print(Ux.shape)

(137724, 109)


In [12]:
ratio_pts = 0.1
ratio_time = 0.5

new_Ux, new_Uy = sample(Ux, Uy, ratio_pts, ratio_time)
print(new_Ux.shape, new_Uy.shape )

ux [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.26693854 0.58790611 1.00216468 ... 3.2887467  3.24233127 3.19520016]
 [0.24344283 0.53419097 0.90760697 ... 2.89713188 2.856109   2.8144547 ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
ux [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.20682261 0.45453152 0.77344346 ... 2.50730752 2.47187426 2.43589505]
 [0.20562973 0.45169863 0.76831573 ... 2.48024956 2.44517638 2.40956297]
 [0.         0.         0.         ... 0.         0.         0.        ]]
ux [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.    

In [ ]:
print(new_Ux.shape)

1. modeliser mathématiquement l’écoulement sanguin à l’aide de PDE dépendante de 2-3 paramètres physique
2. simuler l’écoulement par un code d’éléments fini ou similaire
3. générer beaucoup de solutions avec une grande nombre de paramètres différents. (Les 2-3, pris de façon aléatoire)
4. a. utiliser les solutions numérique pour établir un auto encoder qui au milieu n’ai que 2-5 hyper-paramètres libres  
b. quel erreur on obtient ? Est-ce possible de réduire le nombre d’hyper-paramètres ?
5. étudier s’il y a une rélation entre les 2-5 hyper-paramètre et les paramètres physique  
a. à l’aide de statistiques
5. b. à l’aide d’un DNN (différent de 4a)
6. (optionnel) faire un DNN entre l’input de 4a et output les paramêtres physique. Et/ou l’inverse.
7. Discussion et conclusions 

## 1. Data exploration

## 2. Feature processing

## 3. Solution generation

## 4. Auto-encoder

## 5. Hyper-parameters and physics parameters relationship

## 6. Discussion & conclusion